# Generated by Django 4.2.20 on 2025-05-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
